fetch and merge latest changes from upstream master (#13)
* Fix spacing around multiplication operator (#319)

* Fix prettier check (#321)

* Make spaces after functors consistent (#320)

* nix: refactor Nix flake files (#323)

* Use `\mathit` for multi-letter identifiers (#322)

* Small fixes (#324)

* fix CI problems

Steps taken to address failing the ci prettier check:

1. Install `nodejs` (e.g., by adding `nodejs` to the `environment.systemPackages` section of `/etc/nixos/configuration.nix`).

2. Install `prettier` using the command `npm install --save-dev --save-exact prettier`.

3. Run `npx prettier . --check` and get something like the following output:

   ```
   Checking formatting...
   [warn] package-lock.json
   [warn] package.json
   [warn] README.md
   [warn] Code style issues found in 3 files. Run Prettier to fix.
   ```

   (The `package-lock.json` and `package.json` files are not relevant.  They were added by nodejs; they're not part of our repo.)

4. Run the command `npx prettier README.md --check`. You should get something like  `README.md 21ms`.

Checking `git diff` confirms that the CI prettier check didn't like some of the formatting of `README.md` and running `npx prettier README.md --write` fixed the problem.

* fix ci problem

Steps to fix the `nix fmt` ci failure:

1. In the root directory of the repo, run `nix fmt . -- --check` and get the following output:

   ```
   ./flake.nix
   1 / 1 would have been reformatted
   error: fail on changes
   ```

2. Run `nix fmt` and get the following output:

   ```
    ./flake.nix
    1 / 1 have been reformatted
   ```

Checking `git diff` confirms that the CI `nix fmt` check didn't like some of the formatting of `flake.nix` and running `nix fmt` fixed the problem.

* fix prettier ci problem (again)

Steps to fix ci problem:

1. Run ` nix run nixpkgs#nodePackages.prettier -- --check .` and get output like

   ```
   Checking formatting...
   [warn] package-lock.json
   [warn] package.json
   [warn] README.md
   [warn] Code style issues found in 2 files. Run Prettier to fix.
   ```

2. Run `npx prettier README.md --write` and get output like

   ```
   README.md 33ms
   ```

Checking `git diff` confirms that the CI prettier check didn't like some of the formatting of `README.md` and running `npx prettier README.md --write` fixed the problem.

---------

Co-authored-by: EFanZh <efanzh@gmail.com>
Co-authored-by: Pol Dellaiera <pol.dellaiera@protonmail.com>